alcohol 의 상위 10번째 값 추출 -> 범위 값 변경한후
speeding 의 7 이상의 alcohol데이터들의 평균산출
최종결과만 print 출력

In [ ]:
import seaborn as sns
import pandas as pd
sns.get_dataset_names()
df = sns.load_dataset('car_crashes')
print(df.head())

   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA  


In [ ]:
#정렬
#2번째 column정렬
data = df.sort_values(by = df.columns[2],ascending = False  )
data.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
34   23.9     5.497   10.038          23.661       20.554       688.75   
40   23.9     9.082    9.799          22.944       19.359       858.97   
26   21.4     8.346    9.416          17.976       18.190       816.21   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
11   17.5     9.450    7.175          14.350       15.225       861.18   

    ins_losses abbrev  
34      109.72     ND  
40      116.29     SC  
26       85.15     MT  
43      156.83     TX  
11      120.92     HI

In [ ]:
# alcohol열의 10번째값
ten = data.iloc[9,2]


In [ ]:
data.iloc[:10,2] = ten
data.head(11)
#첫번째부터 10번째까지 10번째 값이 들어간다

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
34   23.9     5.497    5.771          23.661       20.554       688.75   
40   23.9     9.082    5.771          22.944       19.359       858.97   
26   21.4     8.346    5.771          17.976       18.190       816.21   
43   19.4     7.760    5.771          17.654       16.878      1004.75   
11   17.5     9.450    5.771          14.350       15.225       861.18   
18   20.5     7.175    5.771          14.965       20.090      1281.55   
48   23.8     8.092    5.771          23.086       20.706       992.61   
41   19.4     6.014    5.771          19.012       16.684       669.31   
3    22.4     4.032    5.771          21.056       21.280       827.34   
36   19.9     6.368    5.771          18.308       18.706       881.51   
42   19.5     4.095    5.655          15.990       15.795       767.91   

    ins_losses abbrev  
34      109.72     ND  
40      116.29     SC  
26       85.15     MT  
43      156.83     TX  
11      120.92     HI  
18      194.78     LA  
48      152.56     WV  
41       96.87     SD  
3       142.39     AR  
36      178.86     OK  
42      155.57     TN

In [ ]:
#data의 speed >=7이상인곳
result = data[(data['speeding']>=7)]
print("최종 결과물은", result['alcohol'].mean())

최종 결과물은 5.600099999999999


## 작업 유형 1 - 2
**특정 비율만큼의 데이터와 결측치 대체, 전처리 전후 표준편차 비교**

1. 데이터의 첫번째 행부터 70%까지의 데이터를 추출한 후
2. distance의 결측값을 distance의 중앙값으로 대체하고
3. 결측값 전처리 전과 후의 표준편차 비교
4. 전/후 결과값 print로 출력



In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np
sns.get_dataset_names()
df = sns.load_dataset('planets')
print(df.head())

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009


In [ ]:
len(df) #1035개의 행

1035

In [ ]:
len = int(len(df) * 0.7) #70%의 데이터 추출

In [ ]:
df = df[:len]
#전후를 비교하기위해서 copy
df2 = df.copy()
#df2의 결측값을 df 의 중앙값으로 넣는다
df2['distance'] = df2['distance'].fillna(df2['distance'].median())
print('전처리 전 ',np.std(df['distance']))
print('전처리 후',np.std(df2['distance']))

전처리 전  275.0161144074896
전처리 후 267.0513844259766


## 작업유형 2


데이터 수집

In [ ]:
import seaborn as sns
df = sns.load_dataset('penguins')
print(df.head())

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female  


In [ ]:
#데이터에 결측치가 있는지 확인하기
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
# 1. 결측치 제거
# 해당열의 평균값, 비율, 중앙값, 값 직접입력
#해당열의 분포 확인하기
df['sex'].value_counts()
#male 168, female 165

Male      168
Female    165
Name: sex, dtype: int64

In [ ]:
missing = ['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
#for 문을 돌면서 중앙값 넣어주기
for i in missing :
  df[i] = df[i].fillna(df[i].median())
#없는거 male값넣어주기
df['sex'] = df['sex'].fillna('Male')

In [ ]:
#결측치 제거된 것 확인
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [ ]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen           39.10           18.7              181.0   
1  Adelie  Torgersen           39.50           17.4              186.0   
2  Adelie  Torgersen           40.30           18.0              195.0   
3  Adelie  Torgersen           44.45           17.3              197.0   
4  Adelie  Torgersen           36.70           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3       4050.0    Male  
4       3450.0  Female

In [ ]:
#문자열 - Label로 만들어서 컴퓨터가 이해하기 쉬운 형태로 만들어준다
from sklearn.preprocessing import LabelEncoder
label = ['species','island','sex']
df[label] = df[label].apply(LabelEncoder().fit_transform)

In [ ]:
#문자열들이 숫자로 바뀐것 확인가능
df.head()


species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2           39.10           18.7              181.0   
1        0       2           39.50           17.4              186.0   
2        0       2           40.30           18.0              195.0   
3        0       2           44.45           17.3              197.0   
4        0       2           36.70           19.3              193.0   

   body_mass_g  sex  
0       3750.0    1  
1       3800.0    0  
2       3250.0    0  
3       4050.0    1  
4       3450.0    0

In [ ]:
#데이터 타입 확인하기
df.dtypes

species                int64
island                 int64
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                    int64
dtype: object

In [ ]:
#3 데이터 변환, 더미처리
import pandas as pd
category = ['island','sex']
for i in category:
  #해당 리스트 열들이 카테고리 형식으로 바뀐다
  df[i] = df[i].astype('category')

In [ ]:
# island 2면 1 아니면 0, 데이터를 넓게 펴서 이진형으로 바꿔주는걸 더미처리라고 한다
df = pd.get_dummies(df)

In [ ]:
#성능 좋기도 하고아니기도 함
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  
0         0         0         1      0      1  
1         0         0         1      1      0  
2         0         0         1      1      0  
3         0         0         1      0      1  
4         0         0         1      1      0

In [ ]:
#4 파생변수
# 머신러닝 학습할때 변수로 활용해서 사용하기 좋은형태로 만들거임
# 범주화해서 값을 정리해주는것
# 5가지로 범주화할거임
df['body_mass_qcut'] = pd.qcut(df['body_mass_g'],5,labels=False)

In [ ]:
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_qcut  
0         0         0         1      0      1               1  
1         0         0         1      1      0               1  
2         0         0         1      1      0               0  
3         0         0         1      0      1               2  
4         0         0         1      1      0               0

In [ ]:
#데이터를 5가지 범주로 나눈것을 확인할 수 있다
df['body_mass_qcut'].value_counts()

0    71
1    70
2    68
4    68
3    67
Name: body_mass_qcut, dtype: int64

In [ ]:
# 5. 스케일
#help('sklearn.preprocessing')

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# 변수들마다 단위가 다르기때문에 이를 맞춰주기 위해, 특징변수가 영향력을 다르게 미칠 수 있다 -> 범수 단위 조정
scaler = ['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
min = MinMaxScaler()
min.fit(df[scaler])
df[scaler] = min.transform(df[scaler])

In [ ]:
#0~1사이로 조정된것 확인
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0        0.254545       0.666667           0.152542     0.291667   
1        0        0.269091       0.511905           0.237288     0.305556   
2        0        0.298182       0.583333           0.389831     0.152778   
3        0        0.449091       0.500000           0.423729     0.375000   
4        0        0.167273       0.738095           0.355932     0.208333   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_qcut  
0         0         0         1      0      1               1  
1         0         0         1      1      0               1  
2         0         0         1      1      0               0  
3         0         0         1      0      1               2  
4         0         0         1      1      0               0

In [ ]:
#6 데이터분리
from sklearn.model_selection import train_test_split
#전체행과 종속변수를 제외한 열넣어주기
#stratify : 종속변수 기준으로 골고루 데이터 분리하도록
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df['species'],test_size=0.2,stratify=df['species'],random_state=1)

In [ ]:
print('X_train', X_train.shape)
print('X_test',X_test.shape)
print('y_train',y_train.shape)
print('y_test',y_test.shape)

X_train (275, 10)
X_test (69, 10)
y_train (275,)
y_test (69,)


In [ ]:
#7. 모델학습
from sklearn.ensemble import RandomForestClassifier

model1 = RandomForestClassifier()
model1.fit(X_train,y_train)
pred1 = model1.predict(X_test)

In [ ]:
pred1

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model2 = AdaBoostClassifier()
model2.fit(X_train,y_train)
pred2 = model2.predict(X_test)

In [ ]:
pred2

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [ ]:
#8. 앙상블
#서로 다른 모형 보팅
from sklearn.ensemble import VotingClassifier
#voting = soft -> 확률값으로 나타나고, hard로하면 정수형으로 모형의 결과값들을 도출함

clf = VotingClassifier(estimators=[('rf',model1),('ad',model2)], voting = 'hard')
clf.fit(X_train,y_train)
pred3 = clf.predict(X_test)

In [ ]:
pred3

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [ ]:
#9. 모형평가
#회귀랑 분류랑은 평가지표가 완전다르다!
from sklearn.metrics import accuracy_score

print("랜포 정확도",accuracy_score(y_test,pred1))
print("ada 정확도",accuracy_score(y_test,pred2))
print("voting 정확도",accuracy_score(y_test,pred3))



랜포 정확도 1.0
ada 정확도 0.9855072463768116
voting 정확도 1.0


In [ ]:
#10. 하이퍼파라미터 튜닝
#생략해도됨
from sklearn.model_selection import GridSearchCV
#하이퍼파라미터 서칭할 범위 구하기
parameters = {'n_estimators':[50,100],'max_depth':[4,6]}
model4 = RandomForestClassifier()
clf = GridSearchCV(estimator = model4,param_grid=  parameters,cv=3)
clf.fit(X_train,y_train)
print('최적의 파라미터',clf.best_params_)

최적의 파라미터 {'max_depth': 4, 'n_estimators': 50}


In [ ]:
#11. 예측값 저장
#index 무조건 FaLSE로 해줘야한다
pd.DataFrame({'id':y_test.index,'pred':pred3}).to_csv('00300.csv',index=False)

In [ ]:
check = pd.read_csv('00300.csv')

In [ ]:
check.head()

id  pred
0   57     0
1  173     1
2  213     1
3   50     0
4   25     0